---
x-default-python:
  &default-python
  build:
    context: .
  volumes:
    - ./db.sqlite3:/app/db.sqlite3
    - .:/app
  restart: always

services:
  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
  celery-worker:
    <<: *default-python
    command: python -m celery -A CandBechmark worker -l info
    depends_on:
      - redis
  celery-beat:
    <<: *default-python
    command: python -m celery -A CandBechmark beat -l info
    depends_on:
      - redis
  app:
    <<: *default-python
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - celery-beat
      - celery-worker
    ports:
      - "8000:8000"
  bot:
    <<: *default-python
    command: python bot.py
    depends_on:
      - app
  scraper:
    <<: *default-python
    command: python manage.py scrape_hhru
    depends_on:
      - app
      - celery-beat
      - celery-worker
    restart: always