---
x-default-python:
  &default-python
  build:
    context: .
  volumes:
    - .:/app
  restart: always
  env_file: .env
  environment:
    - DJANGO_SETTINGS_MODULE=CandBenchmark.settings
    - PYTHONUNBUFFERED=1
    - DB_HOST=postgres
    - REDIS_HOST=redis

services:
  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "6379:6379"
  celery-worker:
    <<: *default-python
    command: python3 -m celery -A CandBenchmark worker -l info
    depends_on:
      - redis
      - web
  celery-beat:
    <<: *default-python
    command: python3 -m celery -A CandBenchmark beat -l info
    depends_on:
      - redis
      - web
  web:
    <<: *default-python
    command: >
      sh -c "crond && python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py crontab add
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - redis
  bot:
    <<: *default-python
    command: python3 bot.py
    depends_on:
      - web
  scraper:
    <<: *default-python
    command: python3 manage.py scrape_hhru
    depends_on:
      - web
      - celery-beat
      - celery-worker
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - data-postgres:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  data-postgres: null

