---
x-default-python:
  &default-python
  build:
    context: .
  volumes:
    - .:/app
  restart: always
  env_file: .env
  environment:
    - DJANGO_SETTINGS_MODULE=CandBechmark.settings
    - PYTHONUNBUFFERED=1

services:
  redis:
    image: redis:7.2.5-alpine
    restart: always
    expose:
      - 6379
  celery-worker:
    <<: *default-python
    command: python3 -m celery -A CandBechmark worker -l info
    depends_on:
      - redis
      - web
  celery-beat:
    <<: *default-python
    command: python3 -m celery -A CandBechmark beat -l info
    depends_on:
      - redis
      - web
  web:
    <<: *default-python
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
  bot:
    <<: *default-python
    command: python3 bot.py
    depends_on:
      - web
  scraper:
    <<: *default-python
    command: python3 manage.py scrape_hhru
    depends_on:
      - web
      - celery-beat
      - celery-worker
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres: null